series: Basic OpenGL with GLFW
title: 2D Deferred Point Lighting
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use mutliple render passes to render *Infinite* point lights.
language: C++
tags:
  - Graphics
  - Optimization
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: 2D Point Lighting
  - series: Basic OpenGL with GLFW
    title: Rendering to Textures